baseurl: "/html-students" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://htc-ccis1301.github.io/" # the base hostname & protocol for your site
title: "CCIS 1301 HTML"

exclude:
  - "README.md"
  - "Gemfile"
